version: '3.8'

services:
  k6-load-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: k6-load-test
    networks:
      - grafana-network
    restart: no # To avoid start the test again after a crash or finish

networks:
  grafana-network:
    external: true # Already created in my Grafana deployment